version: "3.8"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
        restart: on-failure
        mem_limit: 2g
        environment:
          - discovery.type=single-node
        ports:
          - 9200
        volumes:
          - /var/lib/elasticsearch:/usr/share/elasticsearch/data
        networks:
          - local
        depends_on:
          - fluent-bit
        logging:
          driver: fluentd
          options:
            tag: efk.es
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.0
        restart: on-failure
        mem_limit: 256m
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
          - 5601:5601
        networks:
          - local
        depends_on:
          - fluent-bit
          - elasticsearch
        logging:
          driver: fluentd
          options:
            tag: efk.kibana
    fluent-bit:
        image: fluent/fluent-bit:latest
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        environment:
          - FLB_ES_HOST=elasticsearch
          - FLB_ES_PORT=9200
        ports:
          #- 2020:2020
          - 24224:24224
        volumes:
          - ./conf/:/etc/fluent-bit/:ro
        networks:
          - local
        logging:
          driver: fluentd
          options:
            tag: efk.fluent-bit
networks:
  local:
    driver: bridge
